apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-wallet-deployment
  namespace: mini-wallet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-wallet
  template:
    metadata:
      labels:
        app: mini-wallet
    spec:
      containers:
        - name: api
          image: sudtanj/mini-wallet-microservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mini-wallet-service
  namespace: mini-wallet
  labels:
    app: mini-wallet-service
spec:
  ports:
    - port: 5000
      name: http
      targetPort: 80
  selector:
    app: mini-wallet
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-wallet-ingress
  namespace: mini-wallet
spec:
  ingressClassName: kong
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mini-wallet-service
                port:
                  number: 5000